### ISSUE TITLE
pocketsphinx - No documentation for parameters like "-vad_postspeech".  

### ISSUE THREAD

**Issue by BeanStalka** [cmusphinx/pocketsphinx-android#30]
I have applied the -vad_postspeech parameter to great effect.

I currently have an issues with the volume of the audio the mic is sending and was hoping there was a gain setting similar to the above -vad_postspeech

Can you point me in the direction of any documentaiton for the paramaters that are available to make these changes.

I would like to be able to experiment with them my self instead of having to post an issue every time.

As always, thanks for you help.

**Comment by nshmyrev** [comment]
You can run pocketsphinx_continuous without arguments to get the list of parameters

You can also run `man pocketsphinx_continuous`

There is no extensive documentation on parameters unfortunately since they are not trivial and requier algorithm understanding. See also

https://stackoverflow.com/questions/29076875/the-range-of-variation-for-each-parameter-for-pocketsphinx-continuous-app
